### ISSUE TITLE
Feature request: telescope picker

### ISSUE THREAD

**Issue by mrdgo** [charludo/projectmgr.nvim#12]
Well, I think the title says it all: I would love to see the project selection to be doable via telescope.

Advantages:
- searchable
- easily define custom actions
- have a previewer (this might be a bit more work)

**Comment by charludo** [comment]
Great idea. I'll definitely look into this, though it might be a while, I'm not overly familiar with telescope. I'm also a bit hesitant to make the project non-standalone, so maybe it should be a config option.

If you have any input on this, feel free to start a PR

**Comment by mrdgo** [comment]
[This line](https://github.com/charludo/projectmgr.nvim/blob/d7b27a46aa32445e3ab96f8556648efd4e40762c/lua/projectmgr/manage.lua#L15) causes problems when you try to open a project without a window.

Otherwise this:
```lua
vim.api.nvim_set_keymap(
	"n",
	"<Leader>up",
	'<cmd>lua vim.ui.select(require("projectmgr.db_adapter").get_projects(), { prompt = "Projects" }, function(choice) require("projectmgr.manage").open_project(choice) end)<CR>',
	{}
)
```

can be used with [telescope-ui-select](https://github.com/nvim-telescope/telescope-ui-select.nvim). The advantage is native nvim API and your project would stay standalone :)

**Comment by mrdgo** [comment]
Have you tried using the above snippet to change project? I could not verify if it is me or `require("projectmgr.manage").open_project(choice)` just is not sufficient

**Comment by charludo** [comment]
> Have you tried using the above snippet to change project? I could not verify if it is me or `require("projectmgr.manage").open_project(choice)` just is not sufficient

Hi, super sorry about not getting back to you earlier. I haven't found time for side projects recently :(
I'll do my best to try and integrate this this week.

**Comment by charludo** [comment]
Hi, sorry again it took so long. Check out the feature branch and let me know if this works for you.

I haven't looked into previewers yet; what do you think would make sense here? Maybe just the config of the project?
