### ISSUE TITLE
Dependecy for kkharji/sqlite.lua

### ISSUE THREAD

**Issue by adelarsq** [charludo/projectmgr.nvim#13]
[sqlite.lua](https://github.com/kkharji/sqlite.lua) allow to use the same Lua library on many plugins.

Using It would allow an easier install, mainly for Windows users that is my case.

Also can be easier to install with anothers package manages other than packer (like Plug).

What you think?

**Comment by charludo** [comment]
Hi,

since PR #8 made the project completely stand-alone, I'd rather keep it that way. 

Did you get it to work with Plug and Windows? Anything worth adding to the README?

**Comment by adelarsq** [comment]
> Did you get it to work with Plug and Windows? Anything worth adding to the README?

Wasn't possible since luarocks didn't work as expected. Works with macOS and Linux, but for Windows I still need to figure out how to make it properly.
