### ISSUE TITLE
Tab complete path when adding a project

### ISSUE THREAD

**Issue by bmorashad** [charludo/projectmgr.nvim#2]
It would be cool if path supports tab completion when adding a new project, similar to how `:e[dit]` command works. Otherwise it's bit annoying to copy/paste the path, not a big deal tho

**Comment by bmorashad** [comment]
Great Thanks

**Comment by charludo** [comment]
Hey, thanks for your patience, with the new update, tab completion for paths (and a bunch of other stuff!) is finally added.

Make sure to check the README, the installation with packer has changed!
