### ISSUE TITLE
Got `Error executing vim.schedule lua callback: attempt to index field 'semanticTokensProvider' (a nil value)` when open project

### ISSUE THREAD

**Issue by bhuynhdev** [charludo/projectmgr.nvim#21]
I am using NvChad with ProjectMgr.nvim. I added these lines onto my `custom/plugins.lua`. 
```lua
  {
    "charludo/projectmgr.nvim",
    lazy = false, -- important!
  },
```

Then I run `:ProjectMgr` and <C-a> to add new project. However, whenever I open my Typescript project through ProjectMgr, I always get this error upon entering and exiting Insert mode: `Error executing vim.schedule lua callback, attempt to index field 'semanticTokensProvider'`

![image](https://github.com/charludo/projectmgr.nvim/assets/55563202/7534ce1f-ba0a-4bf3-a053-dbafdbf0ee7c)

My NvChad works fine when executing directly from the command line `nvim <path>`, but not when using `:ProjectMgr`. Would anyone know what are some potential causes of this error message?

**Comment by bhuynhdev** [comment]
Somehow this error goes away if I use `:ProjectMgr` again to switch to another project, then go back to the Typescript project --> No more errors

**Comment by charludo** [comment]
> Somehow this error goes away if I use `:ProjectMgr` again to switch to another project, then go back to the Typescript project --> No more errors

So this only happens at nvim start-up?

Could you try configuring projectmgr to be loaded after/before any relevant LSP plug-ins?

**Comment by charludo** [comment]
In any case, looks to me like this is most likely an upstream issue: https://github.com/neovim/neovim/issues/21588

See also the linked issue in nvim-lspconfig at the bottom of that thread.

**Comment by bhuynhdev** [comment]
I see. I used the `on_init` tips provided in https://github.com/neovim/nvim-lspconfig/issues/2542 and the problem is resolved. I suppose this is more of an NvChad issue, as I had to change the `plugins/configs/lspconfig.lua` in NvChad

**Comment by charludo** [comment]
> I see. I used the `on_init` tips provided in [neovim/nvim-lspconfig#2542](https://github.com/neovim/nvim-lspconfig/issues/2542) and the problem is resolved. I suppose this is more of an NvChad issue, as I had to change the `plugins/configs/lspconfig.lua` in NvChad

Nice, glad to hear you could resolve it! In case you haven't already, opening an issue with NvChad could be helpful for others as well.
