### ISSUE TITLE
swap lsqlite3 to lsqlite3complete

### ISSUE THREAD

**Issue by sagarc03** [charludo/projectmgr.nvim#7]
Hi, let me start by saying great plugin and I appreciate the work you have put in.

I would like to invite you to consider swapping the dependencies from `lsqlite3` to `lsqlite3complete`. The latter doesn't require you to have sqlite3 to be installed on you system, can find more information about his [here](http://lua.sqlite.org/index.cgi/doc/tip/doc/lsqlite3.wiki#installation). This avoids any conflicts with how things are complied for sqlite3 on the host system. If they are compiled using different complier you usually get this error.

```
symbol not found in flat namespace (_sqlite3_enable_load_extension)
```

I swapped the dependencies on my local copy of the plugin and the plugin works just fine.

**Comment by charludo** [comment]
Hi! Thanks for letting me know, I'll look into this. If it's as easy as swapping out the import, feel free to create a PR!
