### ISSUE TITLE
Problem with lsqlite3

### ISSUE THREAD

**Issue by IZenithy** [charludo/projectmgr.nvim#9]
Hello, how are you? I hope that you are doing well!

I have a problem when opening nvim, this massage pop up:
![2022-08-13_17:52:34](https://user-images.githubusercontent.com/82327047/184499468-9173829a-e0b5-4091-bf17-0c8573982959.jpg)

**Comment by charludo** [comment]
Hi! Could be related to #8, do you have lsqlite3 installed on your machine?

**Comment by IZenithy** [comment]
Yes, I installed it
![2022-08-13_20:49:16](https://user-images.githubusercontent.com/82327047/184505172-63391d9a-12b6-4d6a-916f-07d39c2eec4f.jpg)

but it seems like it's trying to search for it in "usr/lib/lua/5.1/"  instead of  "usr/lib/lua/5.4/"

**Comment by sagarc03** [comment]
@IZenithy you also need to install sqlite on your system, [check](https://www.sqlite.org/index.html)

**Comment by IZenithy** [comment]
Installed already

**Comment by sagarc03** [comment]
sorry i read the whole thing wrong!

I am assuming you are using packer when you install this plugin. Packer does this thing where it doesn't throw an error when installing rocks fail. And for some reason it uses your system python to install the all the rocks neovim requires, which points to python not python3. So if you don't have python in your path it fails

Do this to, and try to reinstall.

```lua
local packer = require("packer")
packer.init({
	luarocks = {
		python_cmd = "python3", -- or add the python virtual env you created for neovim doesn't matter
	},
})

```

**Comment by IZenithy** [comment]
I have changed it, but the error is still there

**Comment by charludo** [comment]
Please try updating, @sagarc03's PR could potentially have fixed this if it was indeed an issue with sqlite3 itself.

**Comment by IZenithy** [comment]
I found the problem, Packer rocks don't work for some reason, so I installed it manually with this command:

```
sudo luarocks install --global --lua-version 5.1 lsqlite3complete
```

**Comment by charludo** [comment]
Alright! Sorry I couldn't be of help, but I'm glad you figured it out!
